baseURL = 'http://kwanlung.github.io/'
languageCode = 'en-us'
title = 'DeanHub | Code Is Life'
theme="hugo-coder"
paginate = 20
enableEmoji = true


[markup.highlight]
noClasses = false

[params]
author = "Dean Ng Kwan Lung"
description = "Dean's personal website"
keywords = "blog,developer,personal"
info = ["Software Engineer"]
avatarURL = "/images/dean.png"
rtl = false
colorScheme = "auto"
hideColorSchemeToggle = false
maxSeeAlsoItems = 5
customCSS = []
customSCSS = []
customJS = []
customRemoteJS = []


[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/kwanlung"

[[params.social]]
name = "Gitlab"
icon = "fa fa-2x fa-gitlab"
weight = 2
url = "https://gitlab.com/kwanlung123"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 3
url = "https://twitter.com/nkwanlungggg"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/deanng00/"

[[params.social]]
name = "Instagram"
icon = "fa fa-2x fa-instagram"
weight = 5
url = "https://www.instagram.com/nkwanlungggg/"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "/about/"

[[languages.en.menu.main]]
name = "Tags"
weight = 2
url = "/tags/"

[[languages.en.menu.main]]
name = "Blog"
weight = 3
url = "/posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 4
url = "/projects/"

[taxonomies]
project = "projects"
tag = "tags"



